name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd myportfolio
          npm ci

      # Step 4: Build the Next.js project and handle the public folder under assets
      - name: Build with Next.js
        env:
          NODE_ENV: 'production'
          NEXT_PUBLIC_BASE_PATH: '/My-Portfolio'
        run: |
          cd myportfolio
          npm run build
          # Ensure the public folder from assets is included in the build output
          mkdir -p out/assets/public
          mkdir -p out/public
          cp -r assets/public/* out/assets/public
          cp -r assets/* out/assets
          cp -r public/* out/public  

      # Step 5: Upload the built artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: myportfolio/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 6: Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
